---
title: "BiB Data Dictionary"
output:
  pdf_document:
    includes:
      in_header: data_dict_style.sty
    toc: yes
  html_document: default
---

```{r setup, include = FALSE}
library(knitr)
library(dplyr)
library(pander)


source("C:/repos/bibloadr/R/bib_data_request_functions.R")

varfile <- "C:/repos/bibloadr/examples/variables.txt"

meta <- get_bibloadr_meta(varfile = varfile, type = "varsection")
sourcemeta <- get_bibloadr_meta(varfile = varfile, type = "sourcelong")
codebook <- get_bibloadr_meta(varfile = varfile, type = "code")
stats <- get_bibloadr_stats(varfile = varfile)
meta <- merge(meta, stats, by = "VariableName")
```

```{r dictionary, echo = FALSE}

coding <- function(v) {
  
  c <- filter(codebook, VariableName == v & !is.na(CodeSetName))
  
  codeblock <- ""
  
  if(nrow(c) > 0) {
    
    codeblock <- paste0(c$Value, " = ", c$ValueLabel, "\\\n")
    codeblock <- c(paste0("------------------\\\nCoding [", c$CodeSetName[1], "]:\\\n"), codeblock)
  
  }
  
  return(codeblock)
  
}

vardescription <- function(var) {
  
  value_line = ifelse(var$MeasureType == "Pending", 
                      "{{var$ValueType}} value\\\n",
                      "{{var$MeasureType}}: {{var$ValueType}} value\\\n")
  
  description_line = ifelse(is.na(var$Description), NA, "------------------\\\n{{var$Description}}\\\n")
  
  range_line = ifelse(var$ValueType %in% c("Continuous", "Integer", "Date", "Time"),
                      "------------------\\\nRange {{var$MinValue}} to {{var$MaxValue}}\\\n", NA)
  
  mean_line = ifelse(var$ValueType == "Continuous", "Mean {{var$MeanValue}}\\\n", NA)
  
  var_block <- value_line
  if(!is.na(description_line)) var_block <- c(var_block, description_line)
  if(!is.na(range_line)) var_block <- c(var_block, range_line)
  if(!is.na(mean_line)) var_block <- c(var_block, mean_line)
  var_block <- c(var_block, coding(v = var$VariableName))
  
  return(knit_expand(text = var_block))

}

source <- function(src) {

  src_block <- "
  
# {{src$SourceLongName}}

### Measurement level: {{src$MeasurementLevel}}

Source ID: {{src$SourceName}}

{{src$Description}}

"
  
  return(knit_expand(text = src_block))
  
}




out <- character(0)

for(s in 1:nrow(sourcemeta)) {
  
  out <- c(out, source(src = sourcemeta[s, ]))
  
  meta_bysource <- filter(meta, SourceName == sourcemeta$SourceName[s])
  
  meta_bysource$SectionName <- ifelse(is.na(meta_bysource$SectionName), "<GENERAL SECTION>", meta_bysource$SectionName)
  
  sections <- unique(meta_bysource$SectionName)
  
  for(se in 1:length(sections)) {

    meta_bysection <- filter(meta_bysource, SectionName == sections[se])
    
    section_table <- select(meta_bysection, Variable = VariableName, `Variable Label` = VariableLabel)
    
    if(sections[se] != "<GENERAL SECTION>") {
      
      out <- c(out, knit_expand(text = "## {{sections[se]}}"))
    
    }
    
    for(v in 1:nrow(meta_bysection)) {
      
      section_table$Details[v] <- vardescription(var = meta_bysection[v, ])

    }
    
    panderOptions("keep.line.breaks", TRUE)
    panderOptions("table.alignment.default", "left")
    panderOptions("table.alignment.rownames", "left")
    panderOptions("table.split.table", Inf)
    panderOptions("table.split.cells", c(30, 30, 60))
    
    out <- c(out, pander(section_table))
    
    } 
  
}


```

`r knit(text = out)`
